version: '2'
services:
    master:
        build: .
        restart: unless-stopped
        ports:
            - 3306:3306
        environment:
            - MYSQL_ROOT_PASSWORD=secret
            - MYSQL_REPLICA_USER=replica
            - MYSQL_REPLICA_PASS=secret
        command: ["mysqld", "--log-bin=mysql-bin", "--server-id=1", "--innodb_support_xa=0", "--loose-rpl_semi_sync_master_enabled"]
    slave:
        build: .
        restart: unless-stopped
        ports:
            - 3307:3306
        environment:
            - MYSQL_ROOT_PASSWORD=secret
            - MYSQL_REPLICA_USER=replica
            - MYSQL_REPLICA_PASS=secret
            - MYSQL_MASTER_SERVER=master
            - MYSQL_MASTER_WAIT_TIME=10
        command: ["mysqld", "--log-bin=mysql-bin", "--server-id=2", "--innodb_support_xa=0", "--loose-rpl_semi_sync_slave_enabled"]
